### ISSUE TITLE
The meta data, title and favicon were default of next Js

### ISSUE THREAD

**Issue by JaiSharma1710** [shuklamaneesh23/cf_helper#10]
![image](https://github.com/user-attachments/assets/efa4d408-e38b-4e62-864f-7791fac93d4a)

the project is using the default meta data title and favicon provided by next js this needs to be fixed

**Comment by yatinsharmaa12** [comment]
hey @JaiSharma1710 , This seem fair thank you for pointing this out.

**Comment by JaiSharma1710** [comment]
hi @shuklamaneesh23 and @yatinsharmaa12  i have raised and fixed this issue please look into it and let me know if some changes are needed

**Comment by JaiSharma1710** [comment]
@yatinsharmaa12 can you assign the issue to me??

**Comment by yatinsharmaa12** [comment]
Hey @JaiSharma1710, we have assigned this issue to you.

**Comment by JaiSharma1710** [comment]
thanks @yatinsharmaa12, i have created a PR solving the same issue. you may look into that and let me know if anything else is needed
