### ISSUE TITLE
Scrape Submission Button should be modfied.

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [shuklamaneesh23/cf_helper#17]
The scrape submission button does not look good.

![image](https://github.com/user-attachments/assets/d6284ed0-a02f-44ba-8247-965046cabd78)

The button should be either in the middle or should be equal to the size of the above inputs boxes.

The whole page should be modified, as the title is not in the center, the placeholders are not also not correctly aligned.

**Comment by AMANVISHWAKARMA27** [comment]
@shuklamaneesh23 , kindly assign me the issue so that I can work on it.

**Comment by yatinsharmaa12** [comment]
Hey @AMANVISHWAKARMA27, the issue has been assigned to you.

**Comment by shuklamaneesh23** [comment]
Thanks  @AMANVISHWAKARMA27  for pointing out this issue. Please, make sure to make the submission button equal to the input box not smaller than that. 
Happy contributing!
