### ISSUE TITLE
Theme toggler button

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [shuklamaneesh23/cf_helper#19]
I propose the implementation of theme toggle using a theme-toggler button at the top-right corner of the landing page which can switch the theme from dark to light and vice-versa.

**Comment by AMANVISHWAKARMA27** [comment]
@yatinsharmaa12 , kindly assign me the issue.

**Comment by shuklamaneesh23** [comment]
@AMANVISHWAKARMA27 ,go ahead!
