### ISSUE TITLE
Cursor does not change to pointer on theme toggle buttons

### ISSUE THREAD

**Issue by salonii04** [shuklamaneesh23/cf_helper#26]
The cursor does not change to a pointer when hovering over the theme toggle buttons, which could lead to a less intuitive user experience. Typically, interactive elements like buttons should change the cursor to a pointer (cursor: pointer;) to indicate they are clickable.

Steps to Reproduce:
Navigate to the page with the theme toggle buttons.
Hover over the theme toggle buttons.
Observe that the cursor remains in its default state (not changing to a pointer).

Expected Behavior:
When hovering over the theme toggle buttons, the cursor should change to a pointer to indicate that the buttons are clickable.

Actual Behavior:
The cursor remains in its default state when hovering over the theme toggle buttons, which might confuse users and reduce the perceived interactivity of the element.

**Comment by salonii04** [comment]
hey @shuklamaneesh23 kindly assign this issue to me, so that I can work on it

**Comment by shuklamaneesh23** [comment]
Sure @salonii04 , thanks for raising this issue.
