### ISSUE TITLE
README needs to be more organized, user-friendly, and visually attractive for both contributors and users visiting repository

### ISSUE THREAD

**Issue by salonii04** [shuklamaneesh23/cf_helper#30]
Some changes can be made to make the README file more appealing, they can be:
1. Adding a logo as heading
2. Adding navigation to key sections
3. Adding a visually appealing contributors section to recognize contributors through GitHub profiles.
4. Provide more detailed explanations, notes, or highlights in key areas to guide new users and contributors better.

**Comment by salonii04** [comment]
hey @shuklamaneesh23 , please assign this issue to me, so that I can work on it

**Comment by shuklamaneesh23** [comment]
sure @salonii04 !
Thanks for pointing this out.
