### ISSUE TITLE
Add logo to the website

### ISSUE THREAD

**Issue by salonii04** [shuklamaneesh23/cf_helper#32]
We need to improve the branding of the website by adding the project logo to the header or a suitable location on the main pages. This will enhance the visual identity and professionalism of the website.

**Comment by salonii04** [comment]
hey @shuklamaneesh23 , kindly assign this issue to me so that I can work on it

**Comment by shuklamaneesh23** [comment]
go ahead @salonii04 !

**Comment by shuklamaneesh23** [comment]
Please check the logo design for both dark as well as light screens.

**Comment by salonii04** [comment]
Okay @shuklamaneesh23
