### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by DavidGoyal** [shuklamaneesh23/cf_helper#7]
The home page of website is not responsive.  To reproduce the issue go to home page and see it on mobile view.
![Screenshot 2024-10-01 062910](https://github.com/user-attachments/assets/543a97cc-7677-4b16-95a3-1b441433e41b)

**Comment by yatinsharmaa12** [comment]
hey @DavidGoyal ,This is already listed as an issue #2 , you need to work on that,
